//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wenba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int id { get; set; }
        public int ProjectId { get; set; }
        public string CourseName { get; set; }
        public string CourseNum { get; set; }
        public string CourseDesc { get; set; }
        public string ActiveFlag { get; set; }
        public int TeacherId { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string Status { get; set; }
        public string Site { get; set; }
        public string Comments { get; set; }
        public string Attribute1 { get; set; }
        public string Attribute2 { get; set; }
        public string Attribute3 { get; set; }
        public string Attribute4 { get; set; }
        public string Attribute5 { get; set; }
        public string Attribute6 { get; set; }
        public string Attribute7 { get; set; }
        public string Attribute8 { get; set; }
        public string Attribute9 { get; set; }
        public string Attribute10 { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedate { get; set; }
    }
}
